---
title: "SIR Model with Constant Force of Infection"
author: "Britney He"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(deSolve)
library(reshape2)
library(ggplot2)
```

## The input data from the instructions were as follows:
Initial number of people in each compartment:
S = 10 6 -1, I = 1 and R = 0
Parameters:
$\lambda$ = 0.2 days −1  (this represents a force of infection that's constant at 0.2)
$\gamma$ = 0.1 days −1  (corresponding to an average duration of infection of 10 days)
We want to run the model for 60 days.

```{r}
# MODEL INPUTS:
# Vector storing the initial number of people in each compartment (at timestep 0)
initial_state_values =  c(S = 999999,  # the whole population we are modeling is susceptible to infection
                          I = 1,       # the epidemic starts with a single infected person
                          R = 0)       # there is no prior immunity in the population
# Vector storing the parameters describing the transition rates in units of days^-1
parameters = c(lambda = 0.2,  # the force of infection, which acts on susceptibles
                gamma = 0.1)   # the rate of recovery, which acts on those infected

# TIMESTEPS:
# Vector storing the sequence of timesteps to solve the model at
times = seq(from = 0, to = 60, by = 1)   # from 0 to 60 days in daily intervals

# SIR MODEL FUNCTION: 
sir_model = function(time, state, parameters) {  
    with(as.list(c(state, parameters)), {
      dS = -lambda * S               
      dI = lambda * S - gamma * I    
      dR = gamma * I                
    return(list(c(dS, dI, dR))) 
    })
}

# MODEL OUTPUT (solving the differential equations)
output = as.data.frame(ode(y = initial_state_values, 
                            times = times, 
                            func = sir_model,
                            parms = parameters))
output
```

## Plots

You can also embed plots, for example:

```{r}
output_long <- melt(as.data.frame(output), id = "time")                  # turn output dataset into long format

ggplot(data = output_long,                                               # specify object containing data to plot
       aes(x = time, y = value, colour = variable, group = variable)) +  # assign columns to axes and groups
  geom_line() +                                                          # represent data as lines
  xlab("Time (days)")+                                                   # add label for x axis
  ylab("Number of people") +                                             # add label for y axis
  labs(colour = "Compartment")                                           # add legend title
```


